### ISSUE TITLE
bundle doesn't work on ruby 1.9

### ISSUE THREAD

**Issue by siebertm** [flyingmachine/whoops_rails_logger#5]
Since in the gemspec, there is a `development_dependency("ruby-debug")`, a call to `bundle install` on ruby >= 1.9 fails. 

To fix this, there are 2 possibilities:
- remove the reference to ruby-debug (which I prefer)
- install ruby-debug19 on ruby >= 1.9 (which can lead to inconsistent Gemfile.lock, so this Gefile.lock should be removed from the repo in this case)

What do you prefer?

**Comment by flyingmachine** [comment]
Whoops - I think I'll use this:

```
gem 'ruby-debug-base19', '0.11.23' if RUBY_VERSION.include? '1.9.1'
gem 'ruby-debug19', :platforms => :ruby_19
gem 'ruby-debug', :platforms => :mri_18
```

**Comment by siebertm** [comment]
right, that's alternative no. 3...

**Comment by flyingmachine** [comment]
I've removed ruby-debug. Thanks for bringing this to my attention!
