### ISSUE TITLE
Rails 4 support?

### ISSUE THREAD

**Issue by siebertm** [flyingmachine/whoops_rails_logger#8]
The gemspec currently requires Rails ~> 3, is support for Rails 4 planned?

**Comment by flyingmachine** [comment]
Nothing planned currently - sorry!

**Comment by bingxie** [comment]
I created a pull request to support rails 4.

**Comment by siebertm** [comment]
I'll close this issue then, see #10

**Comment by flyingmachine** [comment]
Thanks, @bingxie! I've pushed this to rubygems

**Comment by bingxie** [comment]
well done!
